name: "Hello World 101-101"
description: "This is a simple hello world action"
author: Artem Lajko
branding:
  icon: "coffee"
  color: "blue"

inputs:
  custom-text:
    description: "Custom text to echo"
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.custom-text }}
