name: "Hello World"
description: "This is a simple hello world action"
author: Artem Lajko

inputs:
  custom-text:
    description: "Custom text to echo"
    required: true
    default: "Override me!"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.custom-text }}
